// Generated by https://quicktype.io

import {Image} from './Image.interface';

export interface CategoriesPaginated {
	count: number;
	page: number;
	totalPages: number;
	data: Category[];
}

export interface Category {
	name: string;
	image: Image;
	id: string;
}
