// Generated by https://quicktype.io

import {CarItemProps} from './Shop.Interface';

export interface OrderResponse {
	count: number;
	page: number;
	totalPages: number;
	data: Order[];
}

export interface Order {
	car: CarItemProps[];
	currency: Currency;
	user: string;
	cost: number;
	createdAt: string;
	updatedAt: string;
	id: string;
}

export enum Currency {
	Usd = 'USD'
}
