import {Subcategory} from './Subcategory.interface';

export interface CarItemProps {
	subcategory: Subcategory;
	cantidad: number;
}
// Generated by https://quicktype.io

export interface MyShopResponse {
	_id: string;
	car: CarItemProps[];
	user: string;
	createdAt: string;
	updatedAt: string;
	__v: number;
}

export interface Category {
	name: string;
	id: string;
}
