// Generated by https://quicktype.io

import {Image} from './Image.interface';

export interface SubcategoryResp {
	count: number;
	page: number;
	totalPages: number;
	data: Subcategory[];
}

export interface Subcategory {
	status: boolean;
	name: string;
	category: Category;
	createdAt: string;
	updatedAt: string;
	images: Image[];
	id: string;
	price: number;
	currency: string;
}

export interface Category {
	name: string;
	id: string;
}
