// Generated by https://quicktype.io

export interface SubcategoryResp {
	count: number;
	page: number;
	totalPages: number;
	data: Subcategory[];
}

export interface Subcategory {
	status: boolean;
	name: string;
	category: Category;
	createdAt: string;
	updatedAt: string;
	image: Image;
	id: string;
}

export interface Category {
	name: string;
	id: string;
}

export interface Image {
	url: string;
	id: string;
}
